FROM openjdk:8-jdk-alpine
MAINTAINER Daren Jacobs <daren.jacobs@fhlbny.com>

ARG user=jenkins
ARG group=jenkins
ARG uid=10000
ARG gid=10000

ENV HOME /home/${user}
ENV VERSION 3.20
RUN addgroup -g ${gid} ${group} && \
    adduser -D -h $HOME -u ${uid} -G ${group} ${user}

RUN \
    apk --update --no-cache add curl && \
    curl --create-dirs -sSLo /usr/share/jenkins/slave.jar https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${VERSION}/remoting-${VERSION}.jar \
    && chmod 755 /usr/share/jenkins \
    && chmod 644 /usr/share/jenkins/slave.jar

USER ${user}
VOLUME /home/${user}
WORKDIR /home/${user}

COPY jenkins-slave /usr/local/bin/jenkins-slave

ENTRYPOINT ["jenkins-slave"]
