FROM darenjacobs/jnlp-slave:3.20.1
MAINTAINER Daren Jacobs <daren.jacobs@fhlbny.com>
LABEL Description ="This Image connects vial JNLP port with addons - full version not Alpine"
USER root
ARG user=jenkins
ENV TZ="America/New_York"

RUN \
    apt-get update && \
    apt-get install -y \
        build-essential \
        bzip2 \
        ca-certificates \
        git \
        jq \
        libssl-dev \
        maven \
        python-dev \
        python-setuptools \
        tzdata \
        vim && \
    easy_install pip && \
    chown -R ${user} /usr/local/bin && \
    chown -R ${user} /usr/local/lib

# Set the timezone
RUN \
    cp /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo "${TZ}" > /etc/timezone


# Install Packer
ENV PACKER_VERSION=1.2.4
ADD https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip /tmp/
RUN \
    cd /tmp && \
    unzip packer_${PACKER_VERSION}_linux_amd64.zip -d /bin && \
    rm /tmp/packer_${PACKER_VERSION}_linux_amd64.zip

# Install Ant
ENV ANT_VERSION 1.10.4
ENV ANT_HOME /opt/ant/apache-ant-${ANT_VERSION}
RUN \
    mkdir -p ${ANT_HOME} && \
    cd /tmp && wget -q https://www.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz && \
    tar zxvf /tmp/apache-ant-${ANT_VERSION}-bin.tar.gz && \
    mv /tmp/apache-ant-${ANT_VERSION} /opt/ant && \
    rm /tmp/apache-ant-${ANT_VERSION}-bin.tar.gz
ENV PATH ${PATH}:/opt/ant/bin

RUN chown ${user}:${user} -R /home/${user}

USER ${user}
RUN pip install --upgrade setuptools --user && \
    pip install ansible apache-libcloud docker-py jinja2 pyaml
