FROM darenjacobs/jnlp-slave:3.20.1-alpine
MAINTAINER Daren Jacobs <daren.jacobs@fhlbny.com>
LABEL Description ="Jenkins JNLP slave. Source for darenjacobs/custom-slave:alpine"
USER root
ARG user=jenkins
ENV TZ="America/New_York"

RUN \
    apk --update --no-cache add bash ca-certificates git jq maven nodejs nodejs-npm openssl python py-pip tzdata wget && \
    apk --update add --virtual build-dependencies python-dev libffi-dev openssl-dev build-base && \
    pip install --upgrade pip cffi && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install Ansible
RUN \
    echo "==> Installing Ansible <==" && \
    pip install ansible && \
    pip install --upgrade pywinrm && \
    apk --update add sshpass openssh-client rsync && \
    apk del build-dependencies && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /etc/ansible   && \
    echo 'localhost' > /etc/ansible/hosts

# Install Packer
RUN echo "==> Installing Packer <=="
ENV PACKER_VERSION=1.2.4
ADD https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip /tmp/
RUN \
    unzip /tmp/packer_${PACKER_VERSION}_linux_amd64.zip -d /bin && \
    rm /tmp/packer_${PACKER_VERSION}_linux_amd64.zip

# Install Ant
RUN echo "==> Installing Ant <=="

ENV ANT_VERSION 1.10.4
ENV ANT_HOME /opt/ant/apache-ant-${ANT_VERSION}
RUN \
    mkdir -p ${ANT_HOME} && \
    cd /tmp && wget -q https://www.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz && \
    tar zxvf /tmp/apache-ant-${ANT_VERSION}-bin.tar.gz && \
    mv /tmp/apache-ant-${ANT_VERSION} /opt/ant && \
    rm /tmp/apache-ant-${ANT_VERSION}-bin.tar.gz
ENV PATH ${PATH}:/opt/ant/apache-ant-${ANT_VERSION}/bin

RUN chown ${user}:${user} -R /home/${user}
USER ${user}
