---
  apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    name: "jenkins-slave"
    labels:
      name: "jenkins-slave"
  spec:
    replicas: 1
    template:
      metadata:
        name: "jenkins-slave"
        labels:
          name: "jenkins-slave"
      spec:
        containers:
          - name: "jenkins-slave"
            image: "darenjacobs/jenkins-swarm-agent:0.04"
            command:
              - "/run.sh"
              - "-master"
            env:
            - name: COMMAND_OPTIONS
              value: "-master http://jenkins-leader-svc.default.svc.cluster.local -username admin -password jestr8 -labels 'jenkins-slave' -exeecutors 20 -fsroot /workspace"
            livenessProbe:
              exec:
                command:
                - sh
                - -c
                - "netstat -tan | grep ESTABLISHED"
              initialDelaySeconds: 60
              timeoutSeconds: 1
