apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker-gradle-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker-gradle-1
    spec:
      containers:

      - image: garland/docker-jnlp-slave-k8s:gradle-0.1
        imagePullPolicy: Always
        securityContext:
          privileged: true
        name: jnlp
        args:
        - 0aaf2f638cf1de4a8aecdf3609aefcbeb9c80ae8216f79b322932d5325b6bbce
        - worker-gradle-1
        env:
        - name: JENKINS_SECRET
          value: 0aaf2f638cf1de4a8aecdf3609aefcbeb9c80ae8216f79b322932d5325b6bbce
        - name: JENKINS_NAME
          value: worker-gradle-1
        - name: JENKINS_LOCATION_URL
          value: http://jenkins-k8s.apteligent.com/
        - name: JENKINS_URL
          value: http://jenkins:8080
        - name: JENKINS_JNLP_URL
          value: http://jenkins:8080/computer/worker-gradle-1/slave-agent.jnlp
        - name: HOME
          value: /home/jenkins
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/docker/jenkins-scratch
          name: volume-1
        - mountPath: /var/run/docker.sock
          name: volume-0
        - mountPath: /home/jenkins
          name: workspace-volume

        workingDir: /home/jenkins

        resources:
          limits:
            cpu: 4000m
            memory: 4000Mi
          requests:
            cpu: 100m
            memory: 50Mi

      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: volume-0
      - hostPath:
          path: /var/lib/docker/jenkins-scratch
        name: volume-1
      - emptyDir: {}
        name: workspace-volume
